# Generated by Django 4.1.7 on 2023-03-11 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdo_ska', '0003_alter_test_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Professy',
            new_name='Profession',
        ),
    ]
