# Generated by Django 4.1.7 on 2023-03-12 07:25

import cdo_ska.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdo_ska', '0005_rename_professy_test_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, upload_to=cdo_ska.models.test_directory_path),
        ),
    ]
